core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# URL patterns for the core app

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    
    # Login & Logout Functionality
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    
    # Products Functionality
    path('get_product_data/', views.get_product_data, name='get_product_data'),
    path('add_product/', views.add_product, name='add_product'),
    path('update_product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete_product/<str:product_code>/', views.delete_product, name='delete_product'),
    
    # Delivery Note Functionality
    path('add_product_to_delivery/<int:product_id>/', views.add_product_to_delivery, name='add_product_to_delivery'),
    path('reset_delivery_note/', views.reset_delivery_note, name='reset_delivery_note'),
    path('remove_product_from_delivery/<str:product_code>/', views.remove_product_from_delivery, name='remove_product_from_delivery'),
    path('clear_delivery_note/', views.clear_delivery_note, name='clear_delivery_note'),
    
    # Reset Password Functionality
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    
]

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

# Create your models here.

class Inventory(models.Model):
    product_code = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    unit_price = models.IntegerField()
    date_added = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.product_code

    def total_price(self):
        return self.quantity * self.unit_price
    

class DeliveryNote(models.Model):
    ACTIVE_CHOICES = [
        (0, 'Inactive'),
        (1, 'Active'),
    ]
    
    delivery_id = models.CharField(max_length=100, unique=True)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, to_field='product_code')
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    tin = models.CharField(max_length=255)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    unit_price = models.IntegerField()
    total_price = models.IntegerField()
    delivery_no = models.IntegerField()
    date = models.DateField(max_length=100)
    active = models.BooleanField(choices=ACTIVE_CHOICES, default=1)

    def __str__(self):
        return self.delivery_id
    
    def save(self, *args, **kwargs):
        if not self.delivery_id:
            last_delivery = DeliveryNote.objects.all().order_by('delivery_id').last()
            if last_delivery:
                last_id = int(last_delivery.delivery_id)
                self.delivery_id = str(last_id + 1)
            else:
                self.delivery_id = '60'
        super(DeliveryNote, self).save(*args, **kwargs)

core/forms.py
from django import forms
from .models import Inventory
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label="Username")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['product_code', 'description', 'quantity', 'unit_price']

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from .forms import CustomLoginForm, InventoryForm
from .models import Inventory, DeliveryNote
from django.contrib import messages
from datetime import datetime

# Create your views here.

@login_required(login_url='login')
def dashboard(request):
    products = Inventory.objects.all()
    delivery_no = request.session.get('delivery_no', 22)
    delivery_note = request.session.get('delivery_note', [])

    # Calculate the grand total price
    grand_total = sum(item['total_price'] for item in delivery_note)
    
    # Fetch all delivery notes
    delivery_notes = DeliveryNote.objects.all()
    
    return render(request, 'dashboard.html', 
            {'products': products, 
                'delivery_no': delivery_no, 
                    'grand_total': grand_total, 
                        'delivery_note': delivery_note,
                            'delivery_notes': delivery_notes})

@login_required(login_url='login')
def get_product_data(request):
    products = Inventory.objects.all()
    product_data = {
        'labels': [product.product_code for product in products],
        'quantities': [product.quantity for product in products],
    }
    return JsonResponse(product_data)

@login_required(login_url='login')
def add_product(request):
    if request.method == 'POST':
        form = InventoryForm(request.POST)
        if form.is_valid():
            product_code = form.cleaned_data['product_code']
            description = form.cleaned_data['description']
            quantity = form.cleaned_data['quantity']
            unit_price = form.cleaned_data['unit_price']

            # Check if the product already exists
            existing_product = Inventory.objects.filter(product_code=product_code).first()

            if existing_product:
                # If the product exists, update its quantity
                existing_product.quantity += quantity
                existing_product.unit_price = unit_price  # Update unit price if needed
                existing_product.description = description  # Update description if needed
                existing_product.save()
                return JsonResponse({'success': True, 'message': f'Updated quantity for {product_code}. New quantity: {existing_product.quantity}'})
            else:
                # If the product does not exist, create a new one
                form.save()
                return JsonResponse({'success': True, 'message': f'Added new product: {product_code}.'})

        return JsonResponse({'success': False, 'message': 'Invalid form data.'})
    else:
        form = InventoryForm()
    return render(request, 'add_product.html', {'form': form})

@login_required(login_url='login')
def update_product(request, product_id):
    product = get_object_or_404(Inventory, id=product_id)
    if request.method == 'POST':
        form = InventoryForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True, 'message': 'Product updated successfully.'})
        return JsonResponse({'success': False, 'message': 'Invalid form data.'})
    else:
        form = InventoryForm(instance=product)
    return render(request, 'update_product.html', {'form': form, 'product': product})

@login_required(login_url='login')
def delete_product(request, product_code):
    product = get_object_or_404(Inventory, product_code=product_code)
    product.delete()
    return redirect('dashboard')

@login_required(login_url='login')
def add_product_to_delivery(request, product_id):
    product = get_object_or_404(Inventory, id=product_id)
    delivery_note = request.session.get('delivery_note', [])
    
    if request.method == 'POST':
        # Check if the product is already in the delivery note
        for item in delivery_note:
            if item['product_code'] == product.product_code:
                # Update the quantity and total price
                if product.quantity > 0:
                    item['quantity'] += 1
                    item['total_price'] = item['quantity'] * item['unit_price']
                    product.quantity -= 1
                    product.save()
                    request.session['delivery_note'] = delivery_note
                    messages.success(request, 'Product quantity updated in delivery note.')
                else:
                    messages.error(request, 'Product is out of stock.')
                break
        else:
            # Add the product as a new item in the delivery note
            if product.quantity > 0:
                product.quantity -= 1
                product.save()
                
                item = {
                    'product_code': product.product_code,
                    'description': product.description,
                    'quantity': 1,  # Assuming 1 unit is added to the delivery note
                    'unit_price': product.unit_price,
                    'total_price': product.unit_price
                }
                delivery_note.append(item)
                request.session['delivery_note'] = delivery_note
                messages.success(request, 'Product added to delivery note.')
            else:
                messages.error(request, 'Product is out of stock.')
    
    return redirect('dashboard')

@login_required(login_url='login')
def remove_product_from_delivery(request, product_code):
    delivery_note = request.session.get('delivery_note', [])
    product = get_object_or_404(Inventory, product_code=product_code)
    
    # Find the product in the delivery note and remove it
    for item in delivery_note:
        if item['product_code'] == product_code:
            delivery_note.remove(item)
            # Increase the quantity of the product in the inventory
            product.quantity += item['quantity']
            product.save()
            request.session['delivery_note'] = delivery_note
            messages.success(request, 'Product removed from delivery note.')
            break
    else:
        messages.error(request, 'Product not found in delivery note.')
    
    return redirect('dashboard')

@login_required(login_url='login')
def reset_delivery_note(request):
    if request.method == 'POST':
        delivery_note = request.session.get('delivery_note', [])
        delivery_no = request.session.get('delivery_no', 22)

        name = request.POST.get('name', '')
        tin = request.POST.get('tin', '')
        address = request.POST.get('address', '')
        date = request.POST.get('date', datetime.now())

        # Check if there are items in the delivery note
        if not delivery_note:
            messages.error(request, 'No items to save.')
            return redirect('dashboard')

        # Archive the current delivery note
        for item in delivery_note:
            inventory_item = get_object_or_404(Inventory, product_code=item['product_code'])
            DeliveryNote.objects.create(
                name=name,
                address=address,
                tin=tin,
                description=item['description'],
                quantity=item['quantity'],
                unit_price=item['unit_price'],
                total_price=item['total_price'],
                delivery_no=delivery_no,
                date=date,
                inventory=inventory_item
            )

        # Reset the delivery note and increment the delivery number
        request.session['delivery_note'] = []
        request.session['delivery_no'] = delivery_no + 1

        messages.success(request, 'Data archived successfully.')
        return redirect('dashboard')

    messages.error(request, 'Invalid request method.')
    return redirect('dashboard')

@login_required(login_url='login')
def clear_delivery_note(request):
    if request.method == 'POST':
        delivery_note = request.session.get('delivery_note', [])
        for item in delivery_note:
            product = Inventory.objects.get(product_code=item['product_code'])
            product.quantity += item['quantity']
            product.save()
        request.session['delivery_note'] = []
        return JsonResponse({'success': True, 'message': 'Delivery note table cleared successfully.'})
    return JsonResponse({'success': False, 'message': 'Invalid request method.'})

@login_required(login_url='login')
def custom_logout(request):
    logout(request)
    return redirect('login')

def custom_login(request):
    if request.method == 'POST':
        form = CustomLoginForm(request, data=request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username_or_email, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
    else:
        form = CustomLoginForm()
    return render(request, 'login.html', {'form': form})

















core/templates/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
</head>

<body>
    <div class="container">
        <h2>Add Product</h2><br><br>
        <form id="addProductForm" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" id="productCode" name="product_code" class="form-control" required>
                <label for="id_product_code">Product Code:</label>
            </div>
            <div class="form-group">
                <input type="text" id="description" name="description" class="form-control" required>
                <label for="id_description">Description:</label>
            </div>
            <div class="form-group">
                <input type="number" id="quantity" name="quantity" class="form-control" required>
                <label for="id_quantity">Quantity:</label>
            </div>
            <div class="form-group">
                <input type="number" step="0.01" id="unitPrice" name="unit_price" class="form-control" required>
                <label for="id_unit_price">Unit Price:</label>
            </div>
            <button type="submit"> + Add</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        document.getElementById('addProductForm').addEventListener('submit', function(event) {
            event.preventDefault();

            const formData = new FormData(this);
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

            fetch("{% url 'add_product' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrfToken,
                },
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: data.message,
                        showConfirmButton: false,
                        timer: 2000
                    }).then(() => {
                        window.location.href = "{% url 'dashboard' %}";
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: data.message,
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
            })
            .catch(error => {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'An error occurred. Please try again.',
                    showConfirmButton: false,
                    timer: 2000
                });
                console.error('Error:', error);
            });
        });
    </script>
</body>

</html>

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
    <title>Active Life Medical - Sign In</title>
</head>
<body>
    <div class="container">
        <form method="post" id="login-form">
            {% csrf_token %}
            <h2 style="text-align: center;">Active Life Medical <br> Sign In</h2><br><br>
            <div class="form-group">
                {{ form.username }}
                {{ form.username.label_tag }}
            </div>
            <div class="form-group">
                {{ form.password }}
                {{ form.password.label_tag }}
            </div>
            <button type="submit" class="btn btn-primary">Sign In</button>
            <div class="additional-links">
                <a href="#"><i class="fa-solid fa-key"></i> Forget Password?</a>
            </div>
        </form>
    </div>
</body>
</html>

core/templates/update_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Product</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
</head>

<body>
    <div class="container">
        <h2>Update Product</h2><br><br>
        <form id="updateProductForm" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="product_code" id="productCode" value="{{ form.product_code.value }}" class="form-control" required>
                <label for="id_product_code">Product Code:</label>
            </div>
            <div class="form-group">
                <input type="text" name="description" id="description" value="{{ form.description.value }}" class="form-control" required>
                <label for="id_description">Description:</label>
            </div>
            <div class="form-group">
                <input type="number" name="quantity" id="quantity" value="{{ form.quantity.value }}" class="form-control" required>
                <label for="id_quantity">Quantity:</label>
            </div>
            <div class="form-group">
                <input type="number" step="0.01" name="unit_price" id="unitPrice" value="{{ form.unit_price.value }}" class="form-control" required>
                <label for="id_unit_price">Unit Price:</label>
            </div>
            <button type="submit">Update</button>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        document.getElementById('updateProductForm').addEventListener('submit', function(event) {
            event.preventDefault();

            const formData = new FormData(this);
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

            fetch("{% url 'update_product' product.id %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrfToken,
                },
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: data.message,
                        showConfirmButton: false,
                        timer: 2000
                    }).then(() => {
                        window.location.href = "{% url 'dashboard' %}";
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: data.message,
                        showConfirmButton: false,
                        timer: 2000
                    });
                }
            })
            .catch(error => {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'An error occurred. Please try again.',
                    showConfirmButton: false,
                    timer: 2000
                });
                console.error('Error:', error);
            });
        });
    </script>
</body>

</html>